#!/system/bin/sh
# CPU Voltage = VSEL*12.5mV + 600 mV
# OMAP3 SPEC: 950mV .. 1350mV
VSEL=60
RATE=800000

#overclocking from userspace with milestone_overclock
insmod /system/lib/modules/overclock_nowplus_22.ko

echo $VSEL >  /proc/overclock/max_vsel
echo $RATE >  /proc/overclock/max_rate

echo "Overclocking ENABLED, max_vsel=$VSEL, max_rate=$RATE"
