#!/system/bin/sh
# CPU Voltage = VSEL*12.5mV + 600 mV
# OMAP3 SPEC: 950mV .. 1350mV
VSEL=60
RATE=800000

#overclocking from userspace with milestone_overclock
insmod /system/lib/modules/overclock_nowplus_22.ko omap2_clk_init_cpufreq_table_addr=0xc004f7cc


echo 0xc032ae98 >  /proc/overclock/cpufreq_stats_update_addr
echo $VSEL >  /proc/overclock/max_vsel
echo $RATE >  /proc/overclock/max_rate

echo "Overclocking ENABLED, max_vsel=$VSEL, max_rate=$RATE"
